### ISSUE TITLE
Missing type `Json` in TYPE_MAP

### ISSUE THREAD

**Issue by oscar-latorre-av** [DeputyApp/singer-tap-deputy#13]
Resource `EmployeeAgreement` has a newly added field (`Config`) which has a new type (`Json`, as reported by the INFO endpoint). This new field type is not accounted for in `TYPE_MAP` in `discover.py`, and is throwing an error every time Stitch (or singer) tries to perform an extraction.

![image](https://user-images.githubusercontent.com/73163339/233025240-4169e066-6242-401d-8a95-096a1ae55bc5.png)

https://github.com/DeputyApp/singer-tap-deputy/blob/6126abafdd7e07613d823c61c84c06235782044f/tap_deputy/discover.py#L64-L71

<details>
  <summary>Logs</summary>

  ```
  $ tap-deputy -c config.json --dev
  WARNING Executing Tap in Dev mode
  DEBUG Starting new HTTPS connection (1): [REDACTED].eu.deputy.com:443
  DEBUG https://[REDACTED].eu.deputy.com:443 "GET /api/v1/resource/Address/INFO HTTP/1.1" 200 208
  INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.2956879138946533, "tags": {"endpoint": "resource_info", "http_status_code": 200, "status": "succeeded"}}
  DEBUG https://[REDACTED].eu.deputy.com:443 "GET /api/v1/resource/Category/INFO HTTP/1.1" 200 177
  INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.1277756690979004, "tags": {"endpoint": "resource_info", "http_status_code": 200, "status": "succeeded"}}
  DEBUG https://[REDACTED].eu.deputy.com:443 "GET /api/v1/resource/Comment/INFO HTTP/1.1" 200 175
  INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.11403942108154297, "tags": {"endpoint": "resource_info", "http_status_code": 200, "status": "succeeded"}}
  DEBUG https://[REDACTED].eu.deputy.com:443 "GET /api/v1/resource/Company/INFO HTTP/1.1" 200 254
  INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.11162185668945312, "tags": {"endpoint": "resource_info", "http_status_code": 200, "status": "succeeded"}}
  DEBUG https://276be407021147.eu.deputy.com:443 "GET /api/v1/resource/CompanyPeriod/INFO HTTP/1.1" 200 166
  INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.09200048446655273, "tags": {"endpoint": "resource_info", "http_status_code": 200, "status": "succeeded"}}
  DEBUG https://[REDACTED].eu.deputy.com:443 "GET /api/v1/resource/Contact/INFO HTTP/1.1" 200 215
  INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.10479259490966797, "tags": {"endpoint": "resource_info", "http_status_code": 200, "status": "succeeded"}}
  DEBUG https://[REDACTED].eu.deputy.com:443 "GET /api/v1/resource/Country/INFO HTTP/1.1" 200 184
  INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.10700106620788574, "tags": {"endpoint": "resource_info", "http_status_code": 200, "status": "succeeded"}}
  DEBUG https://[REDACTED].eu.deputy.com:443 "GET /api/v1/resource/CustomAppData/INFO HTTP/1.1" 200 189
  INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.16899871826171875, "tags": {"endpoint": "resource_info", "http_status_code": 200, "status": "succeeded"}}
  DEBUG https://[REDACTED].eu.deputy.com:443 "GET /api/v1/resource/CustomField/INFO HTTP/1.1" 200 277
  INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.09703683853149414, "tags": {"endpoint": "resource_info", "http_status_code": 200, "status": "succeeded"}}
  DEBUG https://[REDACTED].eu.deputy.com:443 "GET /api/v1/resource/CustomFieldData/INFO HTTP/1.1" 200 410
  INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.1805715560913086, "tags": {"endpoint": "resource_info", "http_status_code": 200, "status": "succeeded"}}
  DEBUG https://[REDACTED].eu.deputy.com:443 "GET /api/v1/resource/Employee/INFO HTTP/1.1" 200 427
  INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.22699999809265137, "tags": {"endpoint": "resource_info", "http_status_code": 200, "status": "succeeded"}}
  DEBUG https://[REDACTED].eu.deputy.com:443 "GET /api/v1/resource/EmployeeAgreement/INFO HTTP/1.1" 200 294
  INFO METRIC: {"type": "timer", "metric": "http_request_duration", "value": 0.22404694557189941, "tags": {"endpoint": "resource_info", "http_status_code": 200, "status": "succeeded"}}
  CRITICAL 'Json'
  Traceback (most recent call last):
    File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
      exec(code, run_globals)
    File "[REDACTED]\.venv\Scripts\tap-deputy.exe\__main__.py", line 7, in <module>
    File "[REDACTED]\.venv\lib\site-packages\singer\utils.py", line 235, in wrapped
      return fnc(*args, **kwargs)
    File "[REDACTED]\.venv\lib\site-packages\tap_deputy\__init__.py", line 50, in main
      sync(client,
    File "[REDACTED]\.venv\lib\site-packages\tap_deputy\sync.py", line 88, in sync
      catalog = discover(client)
    File "[REDACTED]\.venv\lib\site-packages\tap_deputy\discover.py", line 120, in discover
      schema_dict, metadata = get_schema(client, resource_name)
    File "[REDACTED]\.venv\lib\site-packages\tap_deputy\discover.py", line 96, in get_schema
      'type': ['null', TYPE_MAP[field_type]]
  KeyError: 'Json'
  ```
</details>

**Comment by P-Arnold** [comment]
Facing the same issue here, but the change will need to be made in the repo https://github.com/singer-io/tap-deputy .
I believe `'Json': 'object'`should be added to the `TYPE_MAP` referenced above.

**Comment by Bell-Richard2380** [comment]
Having the same issue here and the full integration has stopped.. Is there any chance of a fix for this ASAP?

**Comment by P-Arnold** [comment]
Thanks for your contribution @oscar-latorre-av . That makes sense to me. I will look in to the code a bit more to see if there's a way to handle those empty array values. Or hopefully someone else can help! I have opened a PR with my initial suggestion [here](https://github.com/singer-io/tap-deputy/pull/8)

**Comment by RhysHutchison** [comment]
Appreciate you reaching out @P-Arnold, apologies for not seeing this soon. I'll make sure this channels issues become instantly visible in future!

For now, let me start looking into this issue and see what I can get sorted for you all!
